# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20161019_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='primary_url',
            new_name='primary',
        ),
        migrations.RenameField(
            model_name='url',
            old_name='shorten_url',
            new_name='shorten',
        ),
    ]
