# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161019_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='counter',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество переходов'),
        ),
    ]
