# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-25 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20161019_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='url',
            options={'ordering': ['-counter'], 'verbose_name': 'URL', 'verbose_name_plural': 'URLs'},
        ),
    ]
